name: Discord bot deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ssh server deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USER}}
        key: ${{secrets.PRIVATE_KEY}}
        script: |
          cd discord
          git pull origin main
          npm install
          sudo systemctl daemon-reload
          
